### PR TITLE
fix: Only use Appsero add_plugin_data if the Appsero Client is v1.2.1 or higher

### LINKED ISSUE #2597: Plugin doesn´t activate after installation
### Description

I'm having trouble installing the WP GraphQl plugin.
I'm using Wordpress 6.1 and I've disabled all other plugins to make sure they're not conflicting, but the plugin still refuses to activate and shows this error message:

*******************************************************************************************************************
Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Call to undefined method Appsero\Insights::add_plugin_data() in /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php:78 Stack trace: #0 /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php(81): graphql_init_appsero_telemetry() #1 /home/st01apptechlovese/st01.app.techlove.se/wp-admin/includes/plugin.php(2314): include_once('...') #2 /home/st01apptechlovese/st01.app.techlove.se/wp-admin/plugins.php(192): plugin_sandbox_scrape() #3 {main} thrown in /home/st01apptechlovese/st01.app.techlove.se/wp-content/plugins/wp-graphql/wp-graphql.php on line 78
*******************************************************************************************************************

### Steps to reproduce

1. Select the plugin from admin page i Wordpress 
2. In Plugins i found the plugin by name WP GraphQl and installed it.
3. After installation I tried to ACTIVATE the plugin
4. And then the error message above apears..

### Additional context

Plugins Installed: 
Advanced Custom Field Pro
All-In_one WP Migration
Custom Post Type UI
Duplicate Page
Oh My SVG
Rest API Feature Image
WP Maximum Upload File Size
WP-Rest-API V2 Menus
Yoast

### WPGraphQL Version

1.12.0

### WordPress Version

6.1

### PHP Version

8

### Additional enviornment details

Skärmavbild 2022-11-01 kl  16 54 22

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [X] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Only add plugin data to Appsero if the Appsero client is 1.2.0 or higher

Does this close any currently open issues?
------------------------------------------
closes #2597

### CODE REVIEW

File: wp-graphql.php [hunk 1]
```diff
@@ -74,8 +74,17 @@ function graphql_init_appsero_telemetry() {
 
 	$client = new Appsero\Client( 'cd0d1172-95a0-4460-a36a-2c303807c9ef', 'WP GraphQL', __FILE__ );
 
-	// @phpstan-ignore-next-line
-	$client->insights()->add_plugin_data()->init();
+	// If the Appsero client is version 1.2.0 or higher, add plugin data
+	if (version_compare( $client->version, '1.2.0', '>=' ) ) {
```
Comment (jasonbahl) [inline wp-graphql.php:78]:
```suggestion
	if (version_compare( $client->version, '1.2.1', '>=' ) ) {
```

File: wp-graphql.php [hunk 2]
```diff
@@ -74,8 +74,17 @@ function graphql_init_appsero_telemetry() {
 
 	$client = new Appsero\Client( 'cd0d1172-95a0-4460-a36a-2c303807c9ef', 'WP GraphQL', __FILE__ );
 
-	// @phpstan-ignore-next-line
-	$client->insights()->add_plugin_data()->init();
+	// If the Appsero client is version 1.2.0 or higher, add plugin data
+	if (version_compare( $client->version, '1.2.1', '>=' ) ) {
```
Comment (justlevine) [inline wp-graphql.php:78]: Would it be more future proof if we did a `class/method_exists()` instead of `version_compare`, JIC they remove/rename the method in later release - and even if it would be would we care?

File: wp-graphql.php [hunk 3]
```diff
@@ -74,8 +74,17 @@ function graphql_init_appsero_telemetry() {
...
+		// @phpstan-ignore-next-line
+		$client->insights()->add_plugin_data()->init();
+
+	// Else, initialize without the plugin data
+	} else {
```
Comment (justlevine) [inline wp-graphql.php:83]: I'm not familiar with the Appsero API, but wondering if we can drop the else statement for a _tiny_ codecomplexity improvement e.g.

```php
if( conditional_check() ) { // see comment on version_compare()
  $client->insights()->add_plugin_data();
}

$client->insights()->init();
```

**Review by justlevine — APPROVED** [review]
Looks good, and testing manually with `WP Maximum Upload File Size`, it works as expected.

Left some CodeQuality suggestions that are probably just my penchant for [premature optimization](https://stackify.com/premature-optimization-evil/) and can be ignored.

File: wp-graphql.php (hunk 3 above)
Comment (jasonbahl) [reply wp-graphql.php:83]: @justlevine ya, we can do that. I'll flip it
