### PR TITLE
#1213 - fix tests for PHP 7.4

### LINKED ISSUE #1213: Some tests failing on PHP 7.4
Some tests are failing for PHP 7.4. 

See: https://github.com/wp-graphql/wp-graphql/pull/1212/checks?check_run_id=555268976

### PR DESCRIPTION
**Pull request by jasonbahl**
Fixes tests for php 7.4

closes #1213

### CODE REVIEW

File: tests/wpunit/ModelUserTest.php [hunk 1]
```diff
@@ -1,4 +1,4 @@
-<?php
+~<?php
```
Comment (CodeProKid) [inline tests/wpunit/ModelUserTest.php:1]: @jasonbahl interesting syntax 🤔

Comment (jasonbahl) [reply tests/wpunit/ModelUserTest.php:1]: haha!!! weird that it passes tests

Comment (jasonbahl) [inline tests/wpunit/ModelUserTest.php:1]:
```suggestion
<?php
```
