### PR TITLE
fix: regression to autoloader for bedrock sites

### LINKED ISSUE #2946: Regression: Missing dependencies notice when WPGraphQL is installed as a composer dependency
Ref: 
              @jasonbahl this change is breaking for me on bedrock (and my assumption is _any_ setup using composer + normal packagist), since the autoloader isnt in `wp-graphql/vendor`.

image

_Originally posted by @justlevine in https://github.com/wp-graphql/wp-graphql/pull/2935#discussion_r1340749589_

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This refactors the logic around determining whether the plugin can load or not to play nicer with Bedrock.

Does this close any currently open issues?
------------------------------------------
closes #2946

### CODE REVIEW

File: wp-graphql.php [hunk 1]
```diff
@@ -32,27 +32,59 @@
...
+
+	if ( isset( $composer_config->autoload->files ) ) {
+		foreach ( $composer_config->autoload->files as $file ) {
+			$file_path = __DIR__ . '/' . $file;
+			if ( file_exists( $file_path ) ) {
+				// @phpcs:ignore
+				require_once $file_path;
+			}
+		}
+	}
```
Comment (justlevine) [inline wp-graphql.php:59]: It's only a few files, can we `require_once` them manually instead of pulling in + parsing a json file?

( would also solve `composer.json` including `src/WPGraphQL` both in `files` and in `psr-4` )

File: wp-graphql.php [hunk 2]
```diff
@@ -68,38 +100,27 @@ function graphql_can_load_plugin(): bool {
...
 		// are loaded from the parent project.
-		if ( class_exists( '\WPGraphQL' ) ) {
-			return true;
-		}
+		return true;
 	}
 
-	// If the autoload file exists, load it
-	if ( file_exists( plugin_dir_path( __FILE__ ) . 'vendor/autoload.php' ) ) {
+	// @phpstan-ignore-next-line: this is ignored as the constant could be defined in wp-config, prior to being defined above
```
Comment (justlevine) [inline wp-graphql.php:106]: Instead of ignoring the entire line, I think we can add `define( 'WPGRAPHQL_AUTOLOAD', true );` to `phpstan/constants.php`

File: wp-graphql.php (hunk 1 above)
Comment (jasonbahl) [reply wp-graphql.php:59]: ya, makes sense. I did have it this way in one commit, then reversed it. Seems sensible to re-reverse back to the manual require_once approach.
