### PR TITLE
fix: improve performance of SQL query in the user loader

### LINKED ISSUE #3178: Slow query in User Loader when querying for the public users
### Description

We have encountered a customer issue where the GraphQL endpoints were returning slow responses. When debugging the problem, we found the User Loader generates a slow query to determine if the user is public.

The slow query is generated in the line [/src/Data/Loader/UserLoader.php#L82](https://github.com/wp-graphql/wp-graphql/blob/4fb1694552dda340724ca5ccf5d823256d080baf/src/Data/Loader/UserLoader.php#L82).

```
SELECT DISTINCT
    `post_author`
FROM
    wp_2_posts
WHERE
    (
        (
            post_type = 'post' AND(post_status = 'publish')
        ) OR(
            post_type = 'page' AND(post_status = 'publish')
        ) OR(
            post_type = 'l-page' AND(post_status = 'publish')
        ) OR(
            post_type = 'place' AND(post_status = 'publish')
        )
    ) AND `post_author` IN(1, 2, 3, 4, 5)
LIMIT 5;
```

```
EXPLAIN SELECT DISTINCT post_author FROM wp_2_posts WHERE ( ( post_type = 'post' AND(post_status = 'publish') ) OR( post_type = 'page' AND(post_status = 'publish') ) OR( post_type = 'l-page' AND(post_status = 'publish') ) OR( post_type = 'place' AND(post_status = 'publish') ) ) AND post_author IN(1, 2, 3, 4, 5) LIMIT 5;

+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+------+--------+----------+-----------------------------------------------------+
| id | select_type | table      | partitions | type  | possible_keys                                                                                | key         | key_len | ref  | rows   | filtered | Extra                                               |
+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+------+--------+----------+-----------------------------------------------------+
|  1 | SIMPLE      | wp_2_posts | NULL       | range | post_author,yoast2_index,posts_mime_type_status_index,status_type_sort_date,type_status_date | post_author | 8       | NULL | 258277 |     8.17 | Using index condition; Using where; Using temporary |
+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+------+--------+----------+-----------------------------------------------------+
```

In this case, the query scans 258K rows and takes 8-10 seconds to execute.

The slow query could be optimised with the query below, which returns results in 2 milliseconds.

```
SELECT DISTINCT
    `wp_users`.ID
FROM
    wp_2_posts
INNER JOIN wp_users ON wp_2_posts.post_author = wp_users.ID
WHERE
    (
        (
            post_type = 'post' AND(post_status = 'publish')
        ) OR(
            post_type = 'page' AND(post_status = 'publish')
        ) OR(
            post_type = 'l-page' AND(post_status = 'publish')
        ) OR(
            post_type = 'place' AND(post_status = 'publish')
        )
    ) AND `post_author` IN(1, 2, 3, 4, 5);
```

```
EXPLAIN SELECT DISTINCT wp_users.ID FROM wp_2_posts INNER JOIN wp_users ON wp_2_posts.post_author = wp_users.ID WHERE ( ( post_type = 'post' AND(post_status = 'publish') ) OR( post_type = 'page' AND(post_status = 'publish') ) OR( post_type = 'l-page' AND(post_status = 'publish') ) OR( post_type = 'place' AND(post_status = 'publish') ) ) AND post_author IN(1, 2, 3, 4, 5);
+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+---------------------------------+-------+----------+-------------------------------------------+
| id | select_type | table      | partitions | type  | possible_keys                                                                                | key         | key_len | ref                             | rows  | filtered | Extra                                     |
+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+---------------------------------+-------+----------+-------------------------------------------+
|  1 | SIMPLE      | wp_users   | NULL       | range | PRIMARY,user_login_key,user_nicename,user_email                                              | PRIMARY     | 8       | NULL                            |     5 |   100.00 | Using where; Using index; Using temporary |
|  1 | SIMPLE      | wp_2_posts | NULL       | ref   | post_author,yoast2_index,posts_mime_type_status_index,status_type_sort_date,type_status_date | post_author | 8       | db190.wp_users.ID               | 14054 |     8.17 | Using where; Distinct                     |
+----+-------------+------------+------------+-------+----------------------------------------------------------------------------------------------+-------------+---------+---------------------------------+-------+----------+-------------------------------------------+
```

If you look at the `EXPLAIN`, it scans only 14K rows to fetch the results. 

The current query returns the user ID even when the user doesn't exist in the database. The new query returns the user ID only when the user exists in the database. I also removed the unnecessary `LIMIT` from the query.

Could you please patch the plugin with the optimised query? I'm happy to help with testing or answer any questions.

### Steps to reproduce

The issue can be reproduced from the GraphiQL IDE with the query below.

```
query PostCards {
  posts(first: 5) {
    nodes {
      title
    }
  }
}
```

### Additional context

_No response_

### WPGraphQL Version

1.22.1

### WordPress Version

6.4.5

### PHP Version

8.1

### Additional environment details

I tested this in the older WordPress and plugin versions, but I'm sure it can also be reproducible in the latest versions.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------

This improves the performance of the SQL query in the User Loader that checks whether a user is considered a published author.

Does this close any currently open issues?
------------------------------------------
closes #3178

### CODE REVIEW

File: src/Data/Loader/UserLoader.php [hunk 1]
```diff
@@ -72,15 +72,13 @@ public function get_public_users( array $keys ) {
...
+		$ids   = implode( ', ', $keys );
 
 		global $wpdb;
 
-		$results = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.NoCaching,WordPress.DB.DirectDatabaseQuery.DirectQuery
+		$results = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
 			$wpdb->prepare(
-				"SELECT DISTINCT `post_author` FROM $wpdb->posts $where AND `post_author` IN ( $ids ) LIMIT $count", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare
-				$keys
+				"SELECT DISTINCT `post_author` FROM $wpdb->posts INNER JOIN $wpdb->users ON $wpdb->posts.post_author = $wpdb->users.ID $where AND `post_author` IN ( $ids )" // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared,WordPressVIPMinimum.Variables.RestrictedVariables.user_meta__wpdb__users
```
Comment (sathyapulse) [inline src/Data/Loader/UserLoader.php:81]: I don't know why, but selecting `wp_users.ID` returns the query results much faster. It's not a big difference but I just wanted to share.

```
time mysql -e "SELECT DISTINCT wp_2_posts.post_author FROM wp_2_posts INNER JOIN wp_users ON wp_2_posts.post_author = wp_users.ID WHERE ( ( post_type = 'post' AND(post_status = 'publish') ) OR ( post_type = 'page' AND(post_status = 'publish') ) OR( post_type = 'place' AND(post_status = 'publish') ) ) AND post_author IN (1, 2, 3, 4, 5);"
+-------------+
| post_author |
+-------------+
|           1 |
|          2 |
|         3 |
|         4 |
+-------------+

real	0m0.471s
user	0m0.008s
sys	0m0.000s
```

```
time mysql -e "SELECT DISTINCT wp_users.ID FROM wp_2_posts INNER JOIN wp_users ON wp_2_posts.post_author = wp_users.ID WHERE ( ( post_type = 'post' AND(post_status = 'publish') ) OR ( post_type = 'page' AND(post_status = 'publish') ) OR( post_type = 'place' AND(post_status = 'publish') ) ) AND post_author IN (1, 2, 3, 4, 5);"
+-----+
| ID  |
+-----+
|   1 |
|  2 |
| 3 |
| 4 |
+-----+

real	0m0.010s
user	0m0.004s
sys	0m0.004s
```

Comment (jasonbahl) [reply src/Data/Loader/UserLoader.php]: @sathyapulse Very nice! I've made adjustments based on this suggestion and pushed up the changes. Thanks for digging into this and providing constructive feedback to make this better and faster for everyone! 🙏🏻 🙌🏻
