### PR TITLE
fix: #2448 - Fixes Comment.author connection resolver to properly load both User and CommentAuthor types

### LINKED ISSUE #2448: Author information is not retrieved when pulling post comments.
Hi, 

first of all thanks for your plugin, it's a great plugin.

https://github.com/wp-graphql/wp-graphql/issues/1139 I saw the error here, the issue was closed, but it was closed without being resolved. Looking at the last comment https://github.com/wp-graphql/wp-graphql/issues/1139#issuecomment-580963408 I am having the same error here.

I have a few custom fields for my User type. But **... on User** doesn't work at all. Only .**..on CommentAuthor** data is coming, I have never been able to solve this problem.

I am sharing a sample screenshot of my application below. I made all users public from the "graphql_object_visibility" section. It just gives me the information on **... on CommentAuhor.** I commented and tested as **2 visitors** and **2 registered members**. However, the result is negative.

Wpgraphql-comment-user-connection

Can you please help with this?

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR fixes the resolver for the `Comment.author` connection. 

The current code will only load User objects if the user is logged in. This isn't expected behavior. Instead, the connection should try to load a User and return it if it's considered a public node, otherwise fallback to a CommentAuhor.

Does this close any currently open issues?
------------------------------------------
closes #2448
related: #1139

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
BEFORE:

For non-authenticated requests, the comment author was _always_ loading a `CommentAuthor` type

CleanShot 2022-07-22 at 15 02 35

AFTER:

Now a non-authenticated request will return a mix of `User` and `CommentAuthor` depending on if the author of a Comment is indeed a user, and the user node is safe to be returned publicly

CleanShot 2022-07-22 at 15 01 51

### CODE REVIEW

File: tests/wpunit/CommentObjectQueriesTest.php [hunk 1]
```diff
@@ -666,7 +666,11 @@ public function dataProviderSwitchUser() {
 	public function testQueryingAvatarOnUserAuthorsIsValidForPublicAndAuthenticatedRequests() {
 
 		// create a comment with a guest author as the author
-		$comment_id = $this->createCommentObject();
+		$comment_by_comment_author_id = $this->createCommentObject([
+			'user_id' => 0
+		]);
+
+		$comment_by_user_id = $this->createCommentObject();
```
Comment (justlevine) [inline tests/wpunit/CommentObjectQueriesTest.php:673]: Might be beyond the scope of this PR, but maybe we should clean up these comments at the end of the test?
Worried it might affect #2408, although if it does, i can always handle it there...

Comment (jasonbahl) [reply tests/wpunit/CommentObjectQueriesTest.php:673]: ya, good idea. I'm bad at cleaning up after my tests 🤦🏻‍♂️ 

I'll update.
