### PR TITLE
fix: mutations being added to the schema without enforcing lowercase first letter

### LINKED ISSUE #2624: regression: mutations aren't being added to the schema with lowercase first character
### Description

In v1.13.0, mutations aren't being added to the schema with lcfirst(). 

### Steps to reproduce

1. Register a mutation with an uppercase letter as the starting character of the mutation name:

```php
add_action( 'graphql_register_types', function() {

	register_graphql_mutation( 'CreateSomething', [
		'inputFields' => [ 'test' => [ 'type' => 'String' ] ],
		'outputFields' => [ 'test' => [ 'type' => 'String' ] ],
		'mutateAndGetPayload' => function() {
			return [ 'test' => 'value...' ];
		}
	] );

} );
```

2. Check the schema and you will see the mutation in the Schema with an uppercase first letter: 

CleanShot 2022-11-28 at 13 10 23

In previous versions, this would have registered the mutation with lcfirst (`createSomething` instead of `CreateSomething`)

### Additional context

_No response_

### WPGraphQL Version

1.13.0

### WordPress Version

6.1.1

### PHP Version

8.0

### Additional enviornment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------

This fixes a regression where registering a mutation with an uppercase first letter is added to the schema as a field with an uppercase first letter instead of being transformed to a lowercase-first letter.

- Failing Test: https://github.com/wp-graphql/wp-graphql/actions/runs/3568456806/jobs/5997350686#step:7:752
- Passing Test: https://github.com/wp-graphql/wp-graphql/actions/runs/3568686398/jobs/5997835419

Does this close any currently open issues?
------------------------------------------
closes #2624

### CODE REVIEW

File: src/Type/WPMutationType.php [hunk 1]
```diff
@@ -307,6 +308,7 @@ protected function register_mutation_field() : void {
 					'isPrivate'   => $this->is_private,
 					'type'        => $this->mutation_name . 'Payload',
 					'resolve'     => $this->resolve_mutation,
+					'name'        => Utils::format_field_name( $this->mutation_name ),
```
Comment (justlevine) [inline src/Type/WPMutationType.php:311]: Great catch! I'm noticing that downstream, `TypeRegistry::prepare_fields()` [just does a `lcfirst()`](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Registry/TypeRegistry.php#L892). Not sure it really matters tho.

**Review by justlevine — APPROVED** [review]
Confirmed working locally with external plugins.
before:
image
after:
image

**Comment by jasonbahl** [comment]
> Confirmed working locally with external plugins.

@justlevine is this with the _latest_ commit where I backed out the changes to `WPMutationType` and put them in the `TypeRegistry::prepare_field()` function?

**Comment by justlevine** [comment]
> @justlevine is this with the latest commit where I backed out the changes to WPMutationType and put them in the TypeRegistry::prepare_field() function?

Yep 😎

**Comment by Jonathan-Garber** [comment]
Not sure if this is a good place to put this but it appears this merge has broken our systems when we upgraded to version 1.13.4

```
$field_config['name'] = Utils::format_field_name( $field_config['name'] );
```

https://github.com/jasonbahl/wp-graphql/blob/86962211bb61f09f3a9c1e26690f5f1a97ca5837/src/Utils/Utils.php#L112-L127

This is renaming all of our fields registered and removing "_" characters
'first_name' as defined in our custom object type fields is now becoming 'firstName'
