### PR TITLE
fix: respect `hasPublishedPosts` where arg on unauthenticated `users` queries

### LINKED ISSUE #2961: hasPublishedPosts is being over-ridden with true for unauthenticated requests, even if hasPublishedPosts: POST is being requested
### Description

I have a user (Joe Bloggs) that has published a PAGE but not a POST. When making an unauthenticated request for users with published blog posts, using `users(where: {hasPublishedPosts: POST})`, Joe Bloggs is being returned in the response.

I can see in the commit linked below, that logic was added to force unauthenticated requests to set `hasPublishedPosts: true`, which will return all users that have published either a Page or a Post. I believe that if `hasPublishedPosts: POST` or  `hasPublishedPosts: PAGE` is requested, those values shouldn't get over-ridden with `true`, as anyone who comes up in `POST` or `PAGE` will also come up in `true` anyway, and are considered publicly facing users.

Related PRs/Commits: 
https://github.com/wp-graphql/wp-graphql/pull/1654 
https://github.com/wp-graphql/wp-graphql/commit/53a675c15511951483c8c79a3504b9bf0d3c8cd4

### Steps to reproduce

1. Have a user that has published a PAGE, but not a POST.
2. Run the following query as a logged in/authenticated user, the user will NOT be returned (this is expected behaviour).
3. Run the query again, as public/unauthenticated, the user WILL be returned (this is unexpected behaviour).

**QUERY**
```
query usersWithPublishedPosts {
  users(where: {hasPublishedPosts: POST}) {
    nodes {
      id
      slug
      name
      posts(first: 1) {
        nodes {
          id
        }
      }
    }
  }
}
```

### Additional context

_No response_

### WPGraphQL Version

1.16.0

### WordPress Version

6.2.2

### PHP Version

8.1.9

### Additional environment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [X] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by justlevine**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This PR fixes the logic used in `UserConnectionResolver::get_query_args()` to only set the `has_published_posts` query arg to `true` for unauthenticated users if the `hasPublishedPosts` where arg isnt set in the connection query.

Additionally, the tests for User Connections and Object queries have been refactored into separate classes, as follows:
- `UserObjectQueriesTest` : used solely for single user queries ( i.e. `query { user { ... } }` )
- `UserConnectionQueriesTest`: used solely for user connections: `query { users { ... } }`
- `UserConnectionPaginationTest`: used specifically for testing pagination under various conditions.

In some places, the existing test logic has been expanded to account for authenticated/unauthenticated requests. 

Does this close any currently open issues?
------------------------------------------

Fixes #2961 

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------

- Before: https://github.com/wp-graphql/wp-graphql/actions/runs/6443259029/job/17494980980
image

- After: https://github.com/wp-graphql/wp-graphql/actions/runs/6443319356/job/17495100405?pr=2962
image

Any other comments?
-------------------
Attachments are a possible enum value, but not actually supported by `has_published_posts`. Think we need a graphql_debug() for now and a new enum in v2.0 🤔

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 20.04 (wsl2 + devibox + PHP 8.1.15 )

**WordPress Version:** 6.3.1

### CODE REVIEW

File: tests/wpunit/UserConnectionPaginationTest.php
Comment (justlevine) [inline tests/wpunit/UserConnectionPaginationTest.php:1]: These tests were moved out of `UserConnectionPaginationTest` with no changes to their contents.

File: tests/wpunit/UserConnectionQueriesTest.php [hunk 1]
```diff
@@ -2,506 +2,962 @@
...
+		$ids = wp_list_pluck( $actual['data']['users']['nodes'], 'databaseId' );
+		// There should be 52 users. One published and one unpublished user for each letter of the alphabet.
+		$this->assertEquals( 52, count( $ids ) );
+
+		$this->delete_users();
 	}
 
-	public function testForwardPaginationOrderedByEmailAscending() {
-		// Set the variables to use in the GraphQL query.
+	public function testWithHasPublishedPostsFilter() {
```
Comment (justlevine) [inline tests/wpunit/UserConnectionQueriesTest.php:832]: This is the test relevant to the actual bug fix.

**Review by jasonbahl — APPROVED** [review]
