### PR TITLE
fix: default cat should not be added when other categories are added

### LINKED ISSUE #3269: Uncategorized is added by default when adding a post
### Description

image

image

When adding a post, it adds the 'Uncategorized' category by default. Is there a way to fix this?

### Steps to reproduce

1. Create a create post mutation as in the picture and use it (only two categories are defined)
2. "Uncategorized" is added

### Additional context

_No response_

### WPGraphQL Version

1.29.3

### WordPress Version

 6.7.1

### PHP Version

7.4.33

### Additional environment details

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

### PR DESCRIPTION
**Pull request by jasonbahl**
What does this implement/fix? Explain your changes.
---------------------------------------------------
This fixes a bug where the `createPost` mutation would assign the "default category" to newly created posts even when other categories were explicitly assigned during the mutation. 

The default category should only be assigned if other categories are not assigned during the creation.

- [x] **FAILING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/12798916700/job/35683922462?pr=3271
- [x] **PASSING TEST:** https://github.com/wp-graphql/wp-graphql/actions/runs/12798966725

Does this close any currently open issues?
------------------------------------------
closes #3269 

Any other comments?
-------------------

## Before

Submitting the `createPost` mutation with categories would create the post with the submitted categories, but _also_ include the default category. 

CleanShot 2025-01-15 at 16 32 04

## After

Submitting the `createPost` mutation with categories would create the post with the submitted categories, and **not include** the default category. 

CleanShot 2025-01-15 at 16 32 30

### CODE REVIEW

File: src/Data/PostObjectMutation.php [hunk 1]
```diff
@@ -355,6 +355,13 @@ protected static function set_object_terms( int $post_id, array $input, WP_Post_
 						return;
 					}
 
+					if ( 'category' === $tax_object->name  ) {
```
Comment (justlevine) [inline src/Data/PostObjectMutation.php]: Does the bug happen also when `$append` is false? If not, it would be great to gate against and avoid the unnecessary extra db write.
